### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Dany-LF** [Gizmo-Rishab/ExModule#2]
root@debian:~/test# npm run dev

> exmodule@0.0.0 dev /root/test
> nodemon ./bin/www -e js,ejs

[nodemon] 2.0.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: js,ejs
[nodemon] starting `node ./bin/www.js`
/root/test/bin/www.js:3
import app from '../app.js';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
[nodemon] app crashed - waiting for file changes before starting...

**Comment by Dany-LF** [comment]
Not really important i gtg make my own website with express :)
